language: node_js
node_js:
  - node
cache:
  yarn: true
  directories:
    - node_modules
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: test-techbeach
  # Prevent Travis from deleting your built site so it can be uploaded.
  skip_cleanup: true
  # local_dir: dist
